sudo: false

language: python

python:
  - "2.7"

services:
  - docker

script:
  - sudo pip install tox
  - tox .
  - docker build -t sukujgrg/aflaskapp:latest .
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USERNAME -p $DOCKER_PASSWORD;
  - docker push sukujgrg/aflaskapp:latest;

notifications:
  email:
    recipients:
      - sukujgrg+travis@gmail.com
